### ISSUE TITLE
Unable to create a collection on QA

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/happy-heron#158]
These log messages:

```
I, [2020-10-19T13:31:18.956760 #21373]  INFO -- : [7427bd7b-e5df-4ffa-ac43-81b4f9ec0541] Started POST "/collections" for 171.66.183.192 at 2020-10-19 13:31:18 -0700
I, [2020-10-19T13:31:18.957585 #21373]  INFO -- : [7427bd7b-e5df-4ffa-ac43-81b4f9ec0541] Processing by CollectionsController#create as JS
I, [2020-10-19T13:31:18.957655 #21373]  INFO -- : [7427bd7b-e5df-4ffa-ac43-81b4f9ec0541]   Parameters: {"authenticity_token"=>"Fbe6JN2OYOuDWLJ6749PZvN2u9QGPc3H6ojZvCHJou0ZXz3BshuQXGgAUWxm8qic+sOQzrxbi/XF0GyRGGsslA==", "collection"=>{"name"=>"Justin's test collection", "description"=>"Just for testing h2", "contact_email"=>"jcoyne@justincoyne.com", "visibility"=>"world", "managers"=>"jcoyne85@stanford.edu"}, "commit"=>"Deposit"}
W, [2020-10-19T13:31:18.957814 #21373]  WARN -- : [7427bd7b-e5df-4ffa-ac43-81b4f9ec0541] HTTP Origin header (https://sul-h2-qa.stanford.edu) didn't match request.base_url (http://sul-h2-qa.stanford.edu)
I, [2020-10-19T13:31:18.958084 #21373]  INFO -- : [7427bd7b-e5df-4ffa-ac43-81b4f9ec0541] Completed 422 Unprocessable Entity in 0ms (ActiveRecord: 0.0ms | Allocations: 128)
F, [2020-10-19T13:31:18.958842 #21373] FATAL -- : [7427bd7b-e5df-4ffa-ac43-81b4f9ec0541]
[7427bd7b-e5df-4ffa-ac43-81b4f9ec0541] ActionController::InvalidAuthenticityToken (ActionController::InvalidAuthenticityToken):
[7427bd7b-e5df-4ffa-ac43-81b4f9ec0541]
[7427bd7b-e5df-4ffa-ac43-81b4f9ec0541] actionpack (6.0.3.3) lib/action_controller/metal/request_forgery_protection.rb:215:in `handle_unverified_request'
[7427bd7b-e5df-4ffa-ac43-81b4f9ec0541] actionpack (6.0.3.3) lib/action_controller/metal/request_forgery_protection.rb:247:in `handle_unverified_request'
[7427bd7b-e5df-4ffa-ac43-81b4f9ec0541] devise (4.7.3) lib/devise/controllers/helpers.rb:255:in `handle_unverified_request'
[7427bd7b-e5df-4ffa-ac43-81b4f9ec0541] actionpack (6.0.3.3) lib/action_controller/metal/request_forgery_protection.rb:242:in `verify_authenticity_token'
[7427bd7b-e5df-4ffa-ac43-81b4f9ec0541] activesupport (6.0.3.3) lib/active_support/callbacks.rb:428:in `block in make_lambda'
[7427bd7b-e5df-4ffa-ac43-81b4f9ec0541] activesupport (6.0.3.3) lib/active_support/callbacks.rb:200:in `block (2 levels) in halting'
[7427bd7b-e5df-4ffa-ac43-81b4f9ec0541] actionpack (6.0.3.3) lib/abstract_controller/callbacks.rb:34:in `block (2 levels) in <module:Callbacks>'
[7427bd7b-e5df-4ffa-ac43-81b4f9ec0541] activesupport (6.0.3.3) lib/active_support/callbacks.rb:201:in `block in halting'
[7427bd7b-e5df-4ffa-ac43-81b4f9ec0541] activesupport (6.0.3.3) lib/active_support/callbacks.rb:513:in `block in invoke_before'
[7427bd7b-e5df-4ffa-ac43-81b4f9ec0541] activesupport (6.0.3.3) lib/active_support/callbacks.rb:513:in `each'
[7427bd7b-e5df-4ffa-ac43-81b4f9ec0541] activesupport (6.0.3.3) lib/active_support/callbacks.rb:513:in `invoke_before'
[7427bd7b-e5df-4ffa-ac43-81b4f9ec0541] activesupport (6.0.3.3) lib/active_support/callbacks.rb:134:in `run_callbacks'
[7427bd7b-e5df-4ffa-ac43-81b4f9ec0541] actionpack (6.0.3.3) lib/abstract_controller/callbacks.rb:41:in `process_action'
[7427bd7b-e5df-4ffa-ac43-81b4f9ec0541] actionpack (6.0.3.3) lib/action_controller/metal/rescue.rb:22:in `process_action'
[7427bd7b-e5df-4ffa-ac43-81b4f9ec0541] actionpack (6.0.3.3) lib/action_controller/metal/instrumentation.rb:33:in `block in process_action'
[7427bd7b-e5df-4ffa-ac43-81b4f9ec0541] activesupport (6.0.3.3) lib/active_support/notifications.rb:180:in `block in instrument'
[7427bd7b-e5df-4ffa-ac43-81b4f9ec0541] activesupport (6.0.3.3) lib/active_support/notifications/instrumenter.rb:24:in `instrument'
[7427bd7b-e5df-4ffa-ac43-81b4f9ec0541] activesupport (6.0.3.3) lib/active_support/notifications.rb:180:in `instrument'
[7427bd7b-e5df-4ffa-ac43-81b4f9ec0541] actionpack (6.0.3.3) lib/action_controller/metal/instrumentation.rb:32:in `process_action'
[7427bd7b-e5df-4ffa-ac43-81b4f9ec0541] actionpack (6.0.3.3) lib/action_controller/metal/params_wrapper.rb:245:in `process_action'
[7427bd7b-e5df-4ffa-ac43-81b4f9ec0541] activerecord (6.0.3.3) lib/active_record/railties/controller_runtime.rb:27:in `process_action'
[7427bd7b-e5df-4ffa-ac43-81b4f9ec0541] actionpack (6.0.3.3) lib/abstract_controller/base.rb:136:in `process'
```

**Comment by jcoyne** [comment]
This looks like it might be an issue with our proxy config not sending enough/the right headers through. https://github.com/rails/rails/issues/22965

**Comment by jcoyne** [comment]
@tallenaz fixed this. Thanks Tony!
