### ISSUE TITLE
Fix flappy spec

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/happy-heron#1848]
```
Failure/Error: 
  accept_confirm do
    within '#your-collections' do
      click_link "Delete #{collection_version.name}"
    end
  end

Capybara::ModalNotFound:
  Timed out waiting for modal dialog. Unable to find modal dialog.
./spec/features/delete_draft_collection_spec.rb:21:in `block (4 levels) in <top (required)>'
./spec/support/feature_errors.rb:26:in `block (3 levels) in <top (required)>'
./spec/support/feature_errors.rb:15:in `respond_without_detailed_exceptions'
./spec/support/feature_errors.rb:25:in `block (2 levels) in <top (required)>'
------------------
--- Caused by: ---
Capybara::ModalNotFound:
  Capybara::ModalNotFound
  ./spec/features/delete_draft_collection_spec.rb:21:in `block (4 levels) in <top (required)>'
```

**Comment by justinlittman** [comment]
I can replicate this sporadically. The delete button is nested in several layers of turbo frames. The only thing I can think of is that there is some sort of race condition with UJS and the frames.

Will try adding a slight delay.

**Comment by justinlittman** [comment]
Based on the generated screenshots, it is proceeding to the collection edit page when clicked.
