### ISSUE TITLE
Replacing content with zip file on v2 of a work produces error

### ISSUE THREAD

**Issue by amyehodge** [sul-dlss/happy-heron#2895]
Testing on qa with work https://sul-h2-qa.stanford.edu/works/301.

This work has about 400 files added via the zip file upload on v1.
For v2, I selected the option to replace this content with another single zip file and was unsuccessful.
1. Clicked pencil to edit item. Entered version comment for tests where I was clicking the deposit button.
2. Chose option to upload zip file.
3. Either clicked the button to upload the zip file or dragged the zip file over. File appeared to upload properly -- green bar and check mark.
4. Clicked either save as draft or deposit -- tested this for each upload option, so 4 combinations total.
5. In all for 4 cases, I was shown the screen with the box that says "We're sorry but something went wrong."

**Comment by amyehodge** [comment]
This appeared to trigger a HB error every time as well: https://app.honeybadger.io/projects/77112/faults/90963970

**Comment by justinlittman** [comment]
```
[8464f0d4-e244-4f81-9b1b-7b335977b230] NoMethodError (undefined method `[]=' for nil:NilClass

      existing_params['file'] = existing.file_attachment.blob.signed_id
                     ^^^^^^^^^^):
[8464f0d4-e244-4f81-9b1b-7b335977b230]
[8464f0d4-e244-4f81-9b1b-7b335977b230] app/services/new_version_parameter_filter.rb:20:in `block in filter_attached_files'
[8464f0d4-e244-4f81-9b1b-7b335977b230] app/services/new_version_parameter_filter.rb:18:in `filter_attached_files'
[8464f0d4-e244-4f81-9b1b-7b335977b230] app/services/new_version_parameter_filter.rb:8:in `call'
[8464f0d4-e244-4f81-9b1b-7b335977b230] app/controllers/works_controller.rb:67:in `update'
```
